version: '3.1'

services:
  postgres:
    container_name: order-postgresDB
    image: postgres:14.5-alpine
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order_db
    ports:
      - '5432:5432'
    volumes:
      - order-postgres:/var/lib/postgresql/data
   



volumes:
  order-postgres:
      driver: local
 