version: '3.1'

services:
  postgres:
    image: postgres:14.5-alpine
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=order_db

    ports:
      - 5432:5432
    volumes:
      - order-postgres:/var/lib/postgresql/data


  order:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        - SPRING.DATASOURCE.URL=jdbc:postgresql://postgres:5432/order_db
        - SPRING.DATASOURCE.USERNAME=postgres
        - SPRING.DATASOURCE.PASSWORD=postgres
    ports:
      - 8080:8080

  migrate-up:
    image: redgate/flyway:9-alpine
    profiles:
      - flyway
    command: -url=jdbc:postgresql://postgres:5432/order_db -schemas=orders -user=postgres -password=postgres  migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      - postgres
  
  migrate-down:
    image: redgate/flyway:9-alpine
    profiles:
      - flyway
    command: -url=jdbc:postgresql://postgres:5432/order_db -schemas=orders -user=postgres -password=postgres  undo
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      - postgres
    
volumes:
  order-postgres:
      driver: local
 